config/routes.rb
Rails.application.routes.draw do

  get '/home', to: 'home#home'
  get '/cv', to: 'home#cv'
  get '/work', to: 'home#work'
  get '/lez', to: 'home#lez'
  get '/sdl', to: 'home#sdl'

  root 'home#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def home
	end

	def cv
	end

	def work	
	end

	def lez
	end

	def sdl
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/cv.html.erb
<div class="container">
  <div id="nav">
  	<li><%= link_to('HOME', home_path, class: 'nav-link') %></li> 
  </div>			
<%= image_tag('cv.jpg', class: 'image') %>
</div>

app/views/home/home.html.erb
<div class="container">
<h1>ZHAN WANG</h1>

<nav>
	<li><%= link_to('ABOUT', cv_path, class: 'nav-link') %></li > 
  <li>   |   </li>
  <li><%= link_to('WORK', work_path, class: 'nav-link') %></li>
</nav>
</div>

app/views/home/lez.html.erb
<div class="container">
  <div id="nav">
    <li><%= link_to('HOME', home_path, class: 'nav-link') %></li> 
    <li><%= link_to('WORK', work_path, class: 'nav-link') %></li>
  </div>

	<h3>Lunar Economic Zone</h3>

	<iframe src="https://player.vimeo.com/video/111431567" width="1000" height="562" frameborder="0" class="video" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> 

	<section id="photos">
    <p>
      The 2028 Mid August Day Lunar Mineral Parade is a speculative event which takes place in
      the newly formed Lunar Economic Zone, an administrative agglomeration of Shenzhen and the Moon, on August 15, 2028.
      Coordinated by Zhan Wang, the event is designed to be seen by the mechanical eyes of the world’s media and is an external projection of pomp and ceremony showcasing an emerging resource rich, technology advanced superpower.
    </p>
    <%= image_tag('lunar economic zone/2.jpg', class: 'image') %>
		<%= image_tag('lunar economic zone/3.jpg', class: 'image') %>
		<%= image_tag('lunar economic zone/4.jpg', class: 'image') %>
    <p>
      As the media frenzy descends on the city the world is invited to the grand parade that marks the first consignment of lunar minerals touching down on earth. The parade route takes spectators along the main axis of city from the 10000 meter tall space elevator to the mega ships of the world’s largest mineral port.
    </p>
		<%= image_tag('lunar economic zone/6.jpg', class: 'image') %>
		<%= image_tag('lunar economic zone/7.jpg', class: 'image') %>
    <p>
      As the world’s largest rare earth producer China currently controls 90% of the mineral market. Their recent limits placed upon mineral exports has artificially driven rare earth prices to unprecedented levels. Western nations are scrambling to find their own mineral deposits to counter the Chinese monopoly.
    </p>
		<%= image_tag('lunar economic zone/1.jpg', class: 'image') %>
		<%= image_tag('lunar economic zone/5.jpg', class: 'image') %>
    <p>
      Between documentary and fiction, between propaganda and news the Lunar Economic Zone plays on our fears of a localised resource economy.
    </p>

	</section>
</div>

app/views/home/sdl.html.erb
<div class="container">
  <div id="nav">
  	<li><%= link_to('HOME', home_path, class: 'nav-link') %></li>	
  	<li><%= link_to('WORK', work_path, class: 'nav-link') %></li>
  </div>

	<h3>System D Logistics</h3>
	
  <iframe src="https://player.vimeo.com/video/86366318?color=00ffaa&title=0&byline=0&portrait=0" width="1000" height="562"  frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> 

	<section id="photos">
		<p>
      As an artery of international trade and a crucial part of the global economy, sea born trade routes are heavily monitored by various technologies that enforce regulations and detect irregular activities.The types of economic activities in question are often described as “under the table” and “off the books” as they are not taxed or included in any Gross National Product. Collectively, this type of trade is the world’s second largest economy, worth $10 trillion a year and employs over half of the world’s population.
    </p>
    <%= image_tag('system d logistics/1.jpg', class: 'image') %>
		<%= image_tag('system d logistics/2.jpg', class: 'image') %>
		<%= image_tag('system d logistics/3.jpg', class: 'image') %>
		<%= image_tag('system d logistics/4.jpg', class: 'image') %>
    <p>
      Making an inventory of the illicit items that are contained within 1 pixel of google earth’s view of Mexico City, System D Logistics operates as a covert supply chain to smuggle these items to the US coastline. Deploying various tactics along the shipping route to evade detection, the logistics operation reveals the extraordinary lengths the authorities go to in order to tax an industry that employs the majority of the population. 
    </p>
    <%= image_tag('system d logistics/5.jpg', class: 'image') %>
		<%= image_tag('system d logistics/6.jpg', class: 'image') %>
		<%= image_tag('system d logistics/7.jpg', class: 'image') %>
    <p>
      The technology of surveillance is not infallible, it is full of gaps, cracks and loopholes and is a infrastructural manifestation of the interests of those who profit from the regulation of goods.
    </p>
		<%= image_tag('system d logistics/8.jpg', class: 'image') %>
		<%= image_tag('system d logistics/9.jpg', class: 'image') %>
	</section>
</div>

app/views/home/work.html.erb
<div class="container">
  <div id="nav">
    <li><%= link_to('HOME', home_path, class: 'nav-link') %></li> 
  </div>

    <div id="work-nav">
      <li><%= image_tag('lunar economic zone/2.jpg', class: 'image') %></li>
      <li><%= image_tag('system d logistics/1.jpg', class: 'image') %></li>
    </div>  


  <%= link_to('LUNAR ECONOMIC ZONE', lez_path, class: 'work-link') %>
  <%= link_to('SYSTEM D LOGISTICS', sdl_path, class: 'work-link') %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ZhanSite</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>